name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t druvanand/hello-world-python:0.0.1.RELEASE .
          docker push druvanand/hello-world-python:0.0.1.RELEASE

      - name: Deploy to Cloud Run
        run: |
          terraform init
          terraform apply -auto-approve
